In [1]:
#importing libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
#load data
ml_movie=pd.read_excel(r'C:\Users\swapn\data analysis projects\Movie_collection (5).xlsx')

In [3]:
ml_movie.head()

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   

      Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0  36524.125         138.7               7.825                8.095   
1  35668.655         152.4               7.505                7.650   
2  39912.675         134.6               7.485                7.570   
3  38873.890         119.3               6.895                7.035   
4  39701.585         127.7               6.920                7.070   

   Director_rating  Producer_rating  Critic_rating  Trailer_views  \
0            7.910            7.995           7.94         527367   
1            7.440            7.470           7.44         494055   
2            7.495            7.515           7.44         547051   
3            6.920            7.020           8.26         516279   
4            6.815            7.070           8.26         531448   

  3D_available  Time_taken  Twitter_hastags     Genre  Avg_age_actors  \
0          YES      109.60          223.840  Thriller              23   
1           NO      146.64          243.456     Drama              42   
2           NO      147.88         2022.400    Comedy              38   
3          YES      185.36          225.344     Drama              45   
4           NO      176.48          225.792     Drama              55   

  MPAA_film_rating  Num_multiplex  Start_Tech_Oscar  
0               PG            494                 0  
1               PG            462                 1  
2               PG            458                 0  
3               PG            472                 0  
4               PG            395                 0

In [4]:
ml_movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Collection           506 non-null    int64  
 1   Marketing expense    506 non-null    float64
 2   Production expense   506 non-null    float64
 3   Multiplex coverage   506 non-null    float64
 4   Budget               506 non-null    float64
 5   Movie_length         506 non-null    float64
 6   Lead_ Actor_Rating   506 non-null    float64
 7   Lead_Actress_rating  506 non-null    float64
 8   Director_rating      506 non-null    float64
 9   Producer_rating      506 non-null    float64
 10  Critic_rating        506 non-null    float64
 11  Trailer_views        506 non-null    int64  
 12  3D_available         506 non-null    object 
 13  Time_taken           494 non-null    float64
 14  Twitter_hastags      506 non-null    float64
 15  Genre                506 non-null    obj

In [5]:
#Initial Observations
#1. Missing data on 'Time_taken' column
#2. Unwanted data that do not provide any information: Movie_length & Time_taken
#3. Unknown whether Marketing expense, production expense are in % or in thousands or in 100 thousand. So need to convert collection to the same format for profit analysis


In [6]:
#Performing EDD

In [7]:
ml_movie.tail()

Collection  Marketing expense  Production expense  Multiplex coverage  \
501       44800            21.2526               78.86               0.427   
502       41200            20.9054               78.86               0.427   
503       47800            21.2152               78.86               0.427   
504       44000            22.1918               78.86               0.427   
505       38000            20.9482               78.86               0.427   

        Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
501  36624.115         142.6                8.68                8.775   
502  33996.600         150.2                8.78                8.945   
503  38751.680         164.5                8.83                8.970   
504  37740.670         162.8                8.73                8.845   
505  33496.650         154.3                8.64                8.880   

     Director_rating  Producer_rating  Critic_rating  Trailer_views  \
501            8.620            8.970            6.8         492480   
502            8.770            8.930            7.8         482875   
503            8.855            9.010            7.8         532239   
504            8.800            8.845            6.8         496077   
505            8.680            8.790            6.8         518438   

    3D_available  Time_taken  Twitter_hastags   Genre  Avg_age_actors  \
501           NO      186.96          243.584  Action              27   
502          YES      132.24          263.296  Action              20   
503           NO      109.56          243.824  Comedy              31   
504          YES      158.80          303.520  Comedy              47   
505          YES      205.60          203.040  Comedy              45   

    MPAA_film_rating  Num_multiplex  Start_Tech_Oscar  
501               PG            561                 1  
502               PG            600                 1  
503               PG            576                 1  
504               PG            607                 1  
505               PG            604                 1

In [8]:
null=ml_movie.isnull().values.any()

In [10]:
print(null)

True


In [11]:
null=ml_movie["Collection"].isnull().values.any()
print(null)

False


In [26]:
null=ml_movie["Time_taken"].isnull().values.any()
print(null)

True


In [ ]:
#there are null values in Time_taken column
#Impute null values with mean

In [27]:
ml_movie.Time_taken=ml_movie.Time_taken.fillna(ml_movie.Time_taken.mean())

In [28]:
ml_movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Collection           506 non-null    int64  
 1   Marketing expense    506 non-null    float64
 2   Production expense   506 non-null    float64
 3   Multiplex coverage   506 non-null    float64
 4   Budget               506 non-null    float64
 5   Movie_length         506 non-null    float64
 6   Lead_ Actor_Rating   506 non-null    float64
 7   Lead_Actress_rating  506 non-null    float64
 8   Director_rating      506 non-null    float64
 9   Producer_rating      506 non-null    float64
 10  Critic_rating        506 non-null    float64
 11  Trailer_views        506 non-null    int64  
 12  3D_available         506 non-null    object 
 13  Time_taken           506 non-null    float64
 14  Twitter_hastags      506 non-null    float64
 15  Genre                506 non-null    obj

In [29]:
#deleting unwanted columns - Trailer_views, Twitter_hastags
ml_movie.drop(ml_movie.columns[[11,14]],axis=1, inplace=True)

In [30]:
ml_movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Collection           506 non-null    int64  
 1   Marketing expense    506 non-null    float64
 2   Production expense   506 non-null    float64
 3   Multiplex coverage   506 non-null    float64
 4   Budget               506 non-null    float64
 5   Movie_length         506 non-null    float64
 6   Lead_ Actor_Rating   506 non-null    float64
 7   Lead_Actress_rating  506 non-null    float64
 8   Director_rating      506 non-null    float64
 9   Producer_rating      506 non-null    float64
 10  Critic_rating        506 non-null    float64
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Genre                506 non-null    object 
 14  Avg_age_actors       506 non-null    int64  
 15  MPAA_film_rating     506 non-null    obj

In [31]:
#creating dummy variable for 3D_available data
ml_movie=pd.get_dummies(ml_movie)

In [33]:
del ml_movie['3D_available_NO']

In [34]:
ml_movie.head()

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   

      Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0  36524.125         138.7               7.825                8.095   
1  35668.655         152.4               7.505                7.650   
2  39912.675         134.6               7.485                7.570   
3  38873.890         119.3               6.895                7.035   
4  39701.585         127.7               6.920                7.070   

   Director_rating  Producer_rating  ...  Time_taken  Avg_age_actors  \
0            7.910            7.995  ...      109.60              23   
1            7.440            7.470  ...      146.64              42   
2            7.495            7.515  ...      147.88              38   
3            6.920            7.020  ...      185.36              45   
4            6.815            7.070  ...      176.48              55   

   Num_multiplex  Start_Tech_Oscar  3D_available_YES  Genre_Action  \
0            494                 0                 1             0   
1            462                 1                 0             0   
2            458                 0                 0             0   
3            472                 0                 1             0   
4            395                 0                 0             0   

   Genre_Comedy  Genre_Drama  Genre_Thriller  MPAA_film_rating_PG  
0             0            0               1                    1  
1             0            1               0                    1  
2             1            0               0                    1  
3             0            1               0                    1  
4             0            1               0                    1  

[5 rows x 21 columns]

In [35]:
#Predict whether a movie will win Star Tech Oscar using all the variables
#Logistic Regression

In [36]:
#Step 1: Train the model: independant var - Lead_Actor_Rating, dependant var - Start_Tech_Oscar

In [42]:
X=ml_movie[['Budget']]
y=ml_movie[['Start_Tech_Oscar']]
X.head()
y.head()

Start_Tech_Oscar
0                 0
1                 1
2                 0
3                 0
4                 0

In [43]:
#award was won only when lead actor rating was 1. This implies that it is not a prominent factor that fetches the award for the movie


In [44]:
from sklearn.linear_model import LogisticRegression
m = LogisticRegression()
m.fit(X,y)
m.coef_
m.intercept_
import statsmodels.api as sn
X_const=sn.add_constant(X)
X_const.head()

const     Budget
0    1.0  36524.125
1    1.0  35668.655
2    1.0  39912.675
3    1.0  38873.890
4    1.0  39701.585

In [45]:
import statsmodels.discrete.discrete_model as sm
logit = sm.Logit(y,X_const).fit()
logit.summary()

Optimization terminated successfully.
         Current function value: 0.688641
         Iterations 4


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:       Start_Tech_Oscar   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Wed, 05 Jul 2023   Pseudo R-squ.:               0.0005348
Time:                        14:58:43   Log-Likelihood:                -348.45
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                    0.5414
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.6707      0.805     -0.833      0.405      -2.249       0.908
Budget      1.399e-05   2.29e-05      0.610      0.542   -3.09e-05    5.89e-05
==============================================================================
"""

In [46]:
#confusion matrix
m.predict_proba(X)


array([[0.54540525, 0.45459475],
       [0.54434742, 0.45565258],
       [0.54959124, 0.45040876],
       ...,
       [0.54815778, 0.45184222],
       [0.54690886, 0.45309114],
       [0.54165985, 0.45834015]])

In [48]:
y_pred=m.predict(X)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [49]:
#budget has no influence on movie getting the Start Tech Award 
#consider training the model with Director_rating

In [52]:
X=ml_movie[['Director_rating']]
y=ml_movie[['Start_Tech_Oscar']]
X.head()
y.head()

Start_Tech_Oscar
0                 0
1                 1
2                 0
3                 0
4                 0

In [61]:
from sklearn.linear_model import LogisticRegression
m = LogisticRegression()
m.fit(X,y)
m.coef_
m.intercept_
import statsmodels.api as sn
X_const=sn.add_constant(X)
X_const.head()
mo=LinearDiscriminantAnalysis()
mo.fit(X,y)
LinearDiscriminantAnalysis()
y_pred_lda=mo.predict(X)
y_pred_lda

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [62]:
#confusion matrix
mo.predict_proba(X)

array([[0.55913319, 0.44086681],
       [0.53859696, 0.46140304],
       [0.6473613 , 0.3526387 ],
       ...,
       [0.55828104, 0.44171896],
       [0.54203069, 0.45796931],
       [0.51620278, 0.48379722]])

In [63]:
y_pred=mo.predict(X)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [65]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_true=y, y_pred=y_pred_lda)
print(conf_matrix)

[[210  66]
 [166  64]]


In [66]:
#correct predictions: 210,64

In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(404, 1) (102, 1) (404, 1) (102, 1)


In [68]:
mo=LogisticRegression()

In [69]:
mo.fit(X_train,y_train)

LogisticRegression()

In [70]:
LogisticRegression()

LogisticRegression()

In [71]:
y_test_pred=mo.predict(X_test)

In [72]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [73]:
confusion_matrix(y_test,y_test_pred)

array([[58,  0],
       [44,  0]], dtype=int64)

In [74]:
#true data - 58,0

In [75]:
accuracy_score(y_test,y_test_pred)

0.5686274509803921

In [76]:
#56.8% accuracy

In [77]:
from sklearn import preprocessing
scaler=preprocessing.StandardScaler().fit(X_train)
X_train_s=scaler.transform(X_train)
scaler=preprocessing.StandardScaler().fit(X_test)
X_test_s=scaler.transform(X_test)
X_test_s

array([[ 0.03464272],
       [ 3.08888478],
       [ 0.0792302 ],
       [-1.55935952],
       [-0.12141344],
       [-0.26632274],
       [-0.18829466],
       [-0.40008517],
       [-0.68990375],
       [-0.41123203],
       [-1.50362518],
       [-0.5672882 ],
       [-0.82366618],
       [-1.31412841],
       [ 3.08888478],
       [ 0.74804233],
       [ 0.0792302 ],
       [ 1.22735769],
       [ 0.7926298 ],
       [-0.14370718],
       [ 0.16840515],
       [-0.35549769],
       [-0.21058839],
       [ 0.75918919],
       [-0.33320395],
       [ 0.09037706],
       [-0.29976335],
       [-0.32205708],
       [ 1.8292886 ],
       [-0.40008517],
       [-0.85710679],
       [-0.25517587],
       [-0.19944153],
       [-0.244029  ],
       [ 0.14611141],
       [-0.61187567],
       [-1.86032498],
       [ 3.08888478],
       [-0.86825366],
       [-1.00201608],
       [ 0.17955201],
       [-0.25517587],
       [-0.27746961],
       [-0.94628174],
       [-0.64531628],
       [-0

In [79]:
from sklearn.neighbors import KNeighborsClassifier

In [80]:
mo_1=KNeighborsClassifier(n_neighbors=1)
mo_1.fit(X_train_s,y_train)

KNeighborsClassifier(n_neighbors=1)

In [81]:
confusion_matrix(y_test,mo_1.predict(X_test_s))
accuracy_score(y_test,mo_1.predict(X_test_s))

0.5294117647058824

In [82]:
#accuracy=52.9%

In [83]:
#Conclusion: Linear Regression model is better with greater accuracy 

In [84]:
from sklearn.model_selection import GridSearchCV

In [85]:
params={'n_neighbors':[1,2,3,4,5,6,7,8,9,10]}
grid_search_v=GridSearchCV(KNeighborsClassifier(),params)
grid_search_v.fit(X_train_s,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [86]:
grid_search_v.best_params_

{'n_neighbors': 7}

In [87]:
optimised_KNN=grid_search_v.best_estimator_

In [88]:
confusion_matrix(y_test,y_test_pred)
accuracy_score(y_test,y_test_pred)

0.5686274509803921

In [89]:
#accuracy=56.8% at k=1

In [ ]:
#improving the model

In [108]:
from sklearn.neighbors import KNeighborsClassifier
mo_1=KNeighborsClassifier(n_neighbors=4)
mo_1.fit(X_train_s,y_train)


KNeighborsClassifier(n_neighbors=4)

In [110]:
confusion_matrix(y_test,mo_1.predict(X_test_s))


array([[44, 14],
       [29, 15]], dtype=int64)

In [111]:
accuracy_score(y_test,mo_1.predict(X_test_s))

0.5784313725490197